# Generated by Django 5.1 on 2024-09-09 01:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='/static/images/avatar.svg', max_length=255, null=True, verbose_name='avatar'),
        ),
    ]
